# -*- coding: utf-8 -*-
"""PillCareAgent 300425.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kf9BuWwAZ5wQfm3UtNf8sQfN0KwV4e7h
"""

# === INSTALL
# Install all required Azure, plotting, and PDF packages in one line
!pip install azure-cosmos azure-storage-blob PyPDF2 twilio matplotlib --quiet

# === IMPORTS
# Core imports for HTTP requests, dates, files, visualization, and APIs
import os, io, requests, datetime, traceback, contextlib
from collections import Counter
from azure.cosmos import CosmosClient
from azure.storage.blob import BlobServiceClient
from PyPDF2 import PdfReader
from twilio.rest import Client
import matplotlib.pyplot as plt

# === SECRETS
# These are the API endpoints and keys for Azure AI Agent, Custom Vision, CosmosDB, Twilio, and Blob Storage
# Note: For hackathon judging, these should be placed in a secure env/secrets file in production

# Azure OpenAI endpoint and key (GPT-4o-mini)
OPENAI_ENDPOINT = "https://ai-pillalex2025103799135999.openai.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview"
OPENAI_API_KEY = "DbXSNgTmJ7XKIzYopvXxt1jmwyyKJQVh1fQpXxLOGsXuCRgsQt4wJQQJ99BDACHYHv6XJ3w3AAAAACOGonrX"

# Azure Custom Vision for detecting pills in photo
CUSTOM_VISION_ENDPOINT = "https://pillagentcustomvision-prediction.cognitiveservices.azure.com/"
CUSTOM_VISION_PREDICTION_KEY = "8T6A9y9pdsXQGB32uYLLoS4RVjYPqTFQbZTo1JOOVnC5zXo40z3ZJQQJ99BDACPV0roXJ3w3AAAIACOGP0yl"
CUSTOM_VISION_PROJECT_ID = "e69be093-7e85-4684-97f5-a983fc29077c"
CUSTOM_VISION_ITERATION_NAME = "Pill_Detection_Model_280425"

# Cosmos DB (used for long-term memory and trend history)
COSMOSDB_ENDPOINT = "https://pillagentcosmos.documents.azure.com:443/"
COSMOSDB_KEY = "8hOqrWgFOoah1aU0AF1rLxhLoPY6se6r8flPjuffUIbut80ZFLpL9aJaUIHpmYKfjwTOfQ08WiPrACDbwEg4lw=="
COSMOSDB_DATABASE_ID = "PillAgentDB"
COSMOSDB_CONTAINER_ID = "Mistakes"

# WhatsApp via Twilio (used for human-agent interaction and escalation)
TWILIO_ACCOUNT_SID = "ACe36935cd29e3adeb3dcafd93789705f0"
TWILIO_AUTH_TOKEN = "b672b798f68ced3d33966070c403e1b0"
TWILIO_WHATSAPP_NUMBER = "whatsapp:+14155238886"
USER_WHATSAPP_NUMBER = "whatsapp:+972529270119"
CAREGIVER_WHATSAPP_NUMBER = "whatsapp:+972529270119"

# Azure Blob Storage (used for storing uploaded photos, PDFs, and dashboards)
BLOB_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=pillagentstorage;AccountKey=WW/BUrFFHhki4P9xuwWDdyFizlZqQ32vfzRG61luzfRaUmRf70+f+XUF+sJtQPPmmvBa5UG9sH3V+AStl02egQ==;EndpointSuffix=core.windows.net"
BLOB_CONTAINER_NAME = "pillcare-container"

# === CLIENTS
# Set up all clients once for Azure services (Cosmos, Blob), Twilio, and agent actions
cosmos_client = CosmosClient(COSMOSDB_ENDPOINT, COSMOSDB_KEY)
container = cosmos_client.get_database_client(COSMOSDB_DATABASE_ID).get_container_client(COSMOSDB_CONTAINER_ID)
client = Client(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN)
blob_service = BlobServiceClient.from_connection_string(BLOB_CONNECTION_STRING)
blob_container = blob_service.get_container_client(BLOB_CONTAINER_NAME)

# === UTILITIES
# WhatsApp messaging — used for LLM agent to communicate with user and caregiver

def send_escalation_alert(text):
    msg = client.messages.create(
        from_=TWILIO_WHATSAPP_NUMBER,
        body=text.encode('utf-16', 'surrogatepass').decode('utf-16'),  # Encode and decode to handle emojis
        to=CAREGIVER_WHATSAPP_NUMBER
    )
    print(f"✅ Escalation sent: SID={msg.sid}")

def send_whatsapp_alert(text):
    msg = client.messages.create(
        from_=TWILIO_WHATSAPP_NUMBER,
        body=text.encode('utf-16', 'surrogatepass').decode('utf-16'),  # Encode and decode to handle emojis
        to=USER_WHATSAPP_NUMBER
    )
    print(f"✅ WhatsApp sent: SID={msg.sid}")
# def send_whatsapp_alert(text):
#     msg = client.messages.create(from_=TWILIO_WHATSAPP_NUMBER, body=text, to=USER_WHATSAPP_NUMBER)
#     print(f"✅ WhatsApp sent: SID={msg.sid}")

# def send_escalation_alert(text):
#     msg = client.messages.create(from_=TWILIO_WHATSAPP_NUMBER, body=text, to=CAREGIVER_WHATSAPP_NUMBER)
#     print(f"✅ Escalation sent: SID={msg.sid}")

# Upload any file to Azure Blob — used for photo, prescription PDF, and dashboards

def upload_file_to_blob(local_path, blob_name):
    try:
        with open(local_path, "rb") as data:
            blob_client = blob_container.get_blob_client(blob=blob_name)
            blob_client.upload_blob(data, overwrite=True)
        return blob_client.url
    except Exception as e:
        print("❌ Upload failed:", e)
        return None

# Extract raw text from a scanned prescription PDF

def extract_text_from_pdf(pdf_path):
    reader = PdfReader(pdf_path)
    return "".join(page.extract_text() for page in reader.pages)

# Send message to Azure OpenAI-based PillCare Agent
# This handles the reasoning layer and gives back empathy-driven replies

def ask_pillcare_agent(msg):
    headers = {"Content-Type": "application/json", "api-key": OPENAI_API_KEY}
    payload = {
        "messages": [
            {"role": "system", "content": "You are PillCare Agent to a senior woman. Be concise, helpful, and empathetic.don't ever reply if not 100% sure."},
            {"role": "user", "content": msg}
        ],
        "temperature": 0.7,
        "max_tokens": 100
    }
    try:
        r = requests.post(OPENAI_ENDPOINT, headers=headers, json=payload)
        return r.json()['choices'][0]['message']['content']
    except Exception as e:
        return f"❌ OpenAI Error: {e}"

# Use LLM to convert unstructured prescription text into structured dict format

def parse_prescription_with_llm(text):
    prompt = (
        "Extract prescribed pills and doses into a Python dictionary like {'Advil': 2, 'Attent': 1}. "
        "NO markdown or comments.\n\nPrescription:\n" + text
    )
    reply = ask_pillcare_agent(prompt)
    try:
        import ast
        if reply.startswith("```"):
            reply = reply.split("```")[1].strip()
        return ast.literal_eval(reply)
    except:
        print("❌ Failed to parse:\n", reply)
        return {}

# Detect pills from photo using Azure Custom Vision

def detect_pills_from_photo(image_path):
    url = f"{CUSTOM_VISION_ENDPOINT}/customvision/v3.0/Prediction/{CUSTOM_VISION_PROJECT_ID}/detect/iterations/{CUSTOM_VISION_ITERATION_NAME}/image"
    headers = {"Prediction-Key": CUSTOM_VISION_PREDICTION_KEY, "Content-Type": "application/octet-stream"}
    with open(image_path, "rb") as f:
        r = requests.post(url, headers=headers, data=f)
    return [p["tagName"] for p in r.json().get("predictions", []) if p["probability"] > 0.2]

# Generate dashboard chart based on missed pills per day

def generate_missing_pills_chart(start_date, end_date, user_id="demo_user_001"):
    query = f"""
    SELECT c.date, c.missing_pills FROM c
    WHERE STARTSWITH(c.id, 'monitoring_{user_id}') ORDER BY c.date ASC
    """
    results = list(container.query_items(query=query, enable_cross_partition_query=True))
    dates, counts = [], []
    for row in results:
        if start_date <= row["date"] <= end_date:
            count = sum(row.get("missing_pills", {}).values())
            dates.append(row["date"])
            counts.append(count)
    if not dates:
        return None
    plt.figure(figsize=(10,5))
    plt.bar(dates, counts, color="tomato")
    plt.title("Missing Pills This Week")
    plt.xticks(rotation=45)
    plt.tight_layout()
    path = f"/content/missing_{end_date}.png"
    plt.savefig(path)
    plt.close()
    return path

# Retrieve past 7 days' behavior (pill adherence + photo uploads)

def get_user_behavior_summary(user_id, days=7):
    today = datetime.datetime.utcnow()
    past = today - datetime.timedelta(days=days)
    query = f"""
    SELECT c.date, c.missing_pills, c.photo_uploaded FROM c
    WHERE STARTSWITH(c.id, 'monitoring_{user_id}') ORDER BY c.date DESC
    """
    records = list(container.query_items(query=query, enable_cross_partition_query=True))
    summary = []
    for r in records:
        d = r["date"]
        if past.strftime("%Y-%m-%d") <= d <= today.strftime("%Y-%m-%d"):
            miss = sum(r.get("missing_pills", {}).values())
            photo = "Yes" if r.get("photo_uploaded") else "No"
            summary.append(f"{d}: Missing={miss}, Photo={photo}")
    return "\n".join(summary)

# Ask the LLM if escalation is needed based on trend

def should_escalate(summary):
    prompt = f"Review:\n{summary}\n\nEscalate? Reply only with 'escalate: yes' or 'escalate: no'"
    reply = ask_pillcare_agent(prompt)
    return reply.strip().lower() == "escalate: yes"

# Save the daily memory into CosmosDB for historical trends

def save_record(user_id, date, detected, expected, missing, reply, photo_url, presc_url):
    record = {
        "id": f"monitoring_{user_id}_{date}",
        "user_id": user_id,
        "date": date,
        "detected_pills": detected,
        "expected_pills": expected,
        "missing_pills": missing,
        "agent_reply": reply,
        "photo_uploaded": True,
        "photo_url": photo_url,
        "prescription_url": presc_url,
        "escalation_needed": False,
        "escalated_today": False
    }
    container.upsert_item(record)
    print(f"✅ Saved to CosmosDB: {date}")

# === MAIN EXECUTION FLOW
# This function runs the full daily interaction pipeline: detection → reasoning → memory → messaging

def run_daily_pillcare_check(USER_ID, IMAGE_PATH, PRESCRIPTION_PATH):
    today = datetime.datetime.utcnow().strftime("%Y-%m-%d")
    photo_url = upload_file_to_blob(IMAGE_PATH, f"{USER_ID}/photos/{today}.jpg")
    presc_url = upload_file_to_blob(PRESCRIPTION_PATH, f"{USER_ID}/prescriptions/{today}.pdf")

    prescription_text = extract_text_from_pdf(PRESCRIPTION_PATH)
    expected = parse_prescription_with_llm(prescription_text)
    detected_list = detect_pills_from_photo(IMAGE_PATH)
    detected = Counter(detected_list)
    missing = {pill: qty - detected.get(pill, 0) for pill, qty in expected.items() if detected.get(pill, 0) < qty}

    summary = get_user_behavior_summary(USER_ID)
    agent_prompt = (
        f"Today I detected: {dict(detected)}.\nExpected: {expected}.\nMissing: {missing}.\n"
        f"\ud83d\udcc5 Last 7 days:\n{summary}\nPlease give advice and comment on trend."
        "Add another Response in Romanian in 2–3 sentences."
    )
    reply = ask_pillcare_agent(agent_prompt)
    print("Agent Reply:\n", reply)
    send_whatsapp_alert(reply)

    save_record(USER_ID, today, dict(detected), expected, missing, reply, photo_url, presc_url)

    if should_escalate(summary):
        send_escalation_alert("\ud83d\udea8 Escalation triggered. Please check on the user.")

    week_ago = (datetime.datetime.utcnow() - datetime.timedelta(days=7)).strftime("%Y-%m-%d")
    chart = generate_missing_pills_chart(week_ago, today, user_id=USER_ID)
    if chart:
        chart_url = upload_file_to_blob(chart, f"{USER_ID}/dashboards/{today}.png")
        send_whatsapp_alert(f"\ud83d\udcca Dashboard:\n{chart_url}")

# Example daily run
run_daily_pillcare_check("Alex", "/content/pill_photo.jpeg", "/content/prescription.pdf")